### ISSUE TITLE
大佬，能不能把linux、macos的文件创建时间也做一下

### ISSUE THREAD

**Issue by orestonce** [xiaoqidun/setft#1]
* 我的开源项目正好需要更新文件的创建时间，但我在网上并没找到对应的api，后来 [monkeyWie 介绍](https://github.com/orestonce/m3u8d/issues/46)你的库可以更新文件创建时间。
* 如果你有空并且愿意得话请实现一下linux、macos版本的对应逻辑

**Comment by xiaoqidun** [comment]
在linux下修改ctime到一个特定的值，需要root权限直接操作文件系统元数据，暂时没有找到不用特殊权限可直接修改ctime的系统调用。

**Comment by orestonce** [comment]
哦，好吧

**Comment by monkeyWie** [comment]
有windows够了🤣
